import type { Building } from "@/lib/building/types";

type TranslateFn = (
  key: string,
  params?: Record<string, string | number>,
) => string;

/**
 * Locale-aware demo tower for the home building stack.
 * Structural fields (prices, status, ids) stay fixed; labels come from `demo.*`.
 */
export function getDemoBuilding(t: TranslateFn): Building {
  return {
    id: "bld-sunshine-bole-01",
    name: t("demo.buildingName"),
    subCity: "bole",
    addressLine: t("demo.addressLine"),
    developerName: t("demo.developerName"),
    floors: [
      {
        level: 12,
        label: t("demo.floor12"),
        units: [
          {
            id: "u-12a",
            unitLabel: "12A",
            floor: 12,
            title: t("demo.u12a"),
            bedrooms: 4,
            bathrooms: 3,
            sizeM2: 248,
            price: 185000,
            currency: "USD",
            status: "available",
            listingType: "SALE",
          },
          {
            id: "u-12b",
            unitLabel: "12B",
            floor: 12,
            title: t("demo.u12b"),
            bedrooms: 3,
            bathrooms: 3,
            sizeM2: 210,
            price: 162000,
            currency: "USD",
            status: "reserved",
            listingType: "SALE",
          },
        ],
      },
      {
        level: 8,
        units: [
          {
            id: "u-8a",
            unitLabel: "8A",
            floor: 8,
            title: t("demo.u8a"),
            bedrooms: 3,
            bathrooms: 2,
            sizeM2: 142,
            price: 18500000,
            currency: "ETB",
            status: "available",
            listingType: "SALE",
          },
          {
            id: "u-8b",
            unitLabel: "8B",
            floor: 8,
            title: t("demo.u8b"),
            bedrooms: 3,
            bathrooms: 2,
            sizeM2: 138,
            price: 17800000,
            currency: "ETB",
            status: "available",
            listingType: "SALE",
          },
          {
            id: "u-8c",
            unitLabel: "8C",
            floor: 8,
            title: t("demo.u8c"),
            bedrooms: 2,
            bathrooms: 2,
            sizeM2: 98,
            price: 12100000,
            currency: "ETB",
            status: "sold",
            listingType: "SALE",
          },
        ],
      },
      {
        level: 5,
        units: [
          {
            id: "u-5a",
            unitLabel: "5A",
            floor: 5,
            title: t("demo.u5a"),
            bedrooms: 2,
            bathrooms: 2,
            sizeM2: 104,
            price: 45000,
            currency: "ETB",
            status: "available",
            listingType: "RENT",
          },
          {
            id: "u-5b",
            unitLabel: "5B",
            floor: 5,
            title: t("demo.u5b"),
            bedrooms: 0,
            bathrooms: 1,
            sizeM2: 86,
            price: 38000,
            currency: "ETB",
            status: "reserved",
            listingType: "RENT",
          },
        ],
      },
      {
        level: 2,
        label: t("demo.floor2"),
        units: [
          {
            id: "u-2a",
            unitLabel: "2A",
            floor: 2,
            title: t("demo.u2a"),
            bedrooms: 2,
            bathrooms: 2,
            sizeM2: 112,
            price: 9800000,
            currency: "ETB",
            status: "available",
            listingType: "OFF_PLAN",
          },
          {
            id: "u-2b",
            unitLabel: "2B",
            floor: 2,
            title: t("demo.u2b"),
            bedrooms: 3,
            bathrooms: 2,
            sizeM2: 136,
            price: 12500000,
            currency: "ETB",
            status: "available",
            listingType: "OFF_PLAN",
          },
          {
            id: "u-2c",
            unitLabel: "2C",
            floor: 2,
            title: t("demo.u2c"),
            bedrooms: 3,
            bathrooms: 3,
            sizeM2: 168,
            price: 15200000,
            currency: "ETB",
            status: "reserved",
            listingType: "OFF_PLAN",
          },
        ],
      },
      {
        level: 0,
        label: t("demo.floor0"),
        units: [
          {
            id: "u-0a",
            unitLabel: "G1",
            floor: 0,
            title: t("demo.u0a"),
            sizeM2: 64,
            price: 72000,
            currency: "ETB",
            status: "available",
            listingType: "RENT",
          },
          {
            id: "u-0b",
            unitLabel: "G2",
            floor: 0,
            title: t("demo.u0b"),
            sizeM2: 52,
            price: 64000,
            currency: "ETB",
            status: "sold",
            listingType: "RENT",
          },
        ],
      },
    ],
  };
}
