import type { Building } from "@/lib/building/types";

/** Demo tower used on the index structural visualization. */
export const DEMO_BUILDING: Building = {
  id: "bld-sunshine-bole-01",
  name: "Sunshine Heights",
  subCity: "bole",
  addressLine: "Bole Road · Block C",
  developerName: "Sunshine Homes PLC",
  floors: [
    {
      level: 12,
      label: "Floor 12 · Penthouse",
      units: [
        {
          id: "u-12a",
          unitLabel: "12A",
          floor: 12,
          title: "Corner penthouse",
          bedrooms: 4,
          bathrooms: 3,
          sizeM2: 248,
          price: 185000,
          currency: "USD",
          status: "available",
          listingType: "SALE",
        },
        {
          id: "u-12b",
          unitLabel: "12B",
          floor: 12,
          title: "Sky terrace suite",
          bedrooms: 3,
          bathrooms: 3,
          sizeM2: 210,
          price: 162000,
          currency: "USD",
          status: "reserved",
          listingType: "SALE",
        },
      ],
    },
    {
      level: 8,
      units: [
        {
          id: "u-8a",
          unitLabel: "8A",
          floor: 8,
          title: "East-facing 3BR",
          bedrooms: 3,
          bathrooms: 2,
          sizeM2: 142,
          price: 18500000,
          currency: "ETB",
          status: "available",
          listingType: "SALE",
        },
        {
          id: "u-8b",
          unitLabel: "8B",
          floor: 8,
          title: "Family 3BR",
          bedrooms: 3,
          bathrooms: 2,
          sizeM2: 138,
          price: 17800000,
          currency: "ETB",
          status: "available",
          listingType: "SALE",
        },
        {
          id: "u-8c",
          unitLabel: "8C",
          floor: 8,
          title: "Compact 2BR",
          bedrooms: 2,
          bathrooms: 2,
          sizeM2: 98,
          price: 12100000,
          currency: "ETB",
          status: "sold",
          listingType: "SALE",
        },
      ],
    },
    {
      level: 5,
      units: [
        {
          id: "u-5a",
          unitLabel: "5A",
          floor: 5,
          title: "Garden-view 2BR",
          bedrooms: 2,
          bathrooms: 2,
          sizeM2: 104,
          price: 45000,
          currency: "ETB",
          status: "available",
          listingType: "RENT",
        },
        {
          id: "u-5b",
          unitLabel: "5B",
          floor: 5,
          title: "Office-ready shell",
          bedrooms: 0,
          bathrooms: 1,
          sizeM2: 86,
          price: 38000,
          currency: "ETB",
          status: "reserved",
          listingType: "RENT",
        },
      ],
    },
    {
      level: 2,
      label: "Floor 2 · Off-plan frame",
      units: [
        {
          id: "u-2a",
          unitLabel: "2A",
          floor: 2,
          title: "Unfinished kitchen framework",
          bedrooms: 2,
          bathrooms: 2,
          sizeM2: 112,
          price: 9800000,
          currency: "ETB",
          status: "available",
          listingType: "OFF_PLAN",
        },
        {
          id: "u-2b",
          unitLabel: "2B",
          floor: 2,
          title: "Core & shell dual-aspect",
          bedrooms: 3,
          bathrooms: 2,
          sizeM2: 136,
          price: 12500000,
          currency: "ETB",
          status: "available",
          listingType: "OFF_PLAN",
        },
        {
          id: "u-2c",
          unitLabel: "2C",
          floor: 2,
          title: "Allocated duplex shell",
          bedrooms: 3,
          bathrooms: 3,
          sizeM2: 168,
          price: 15200000,
          currency: "ETB",
          status: "reserved",
          listingType: "OFF_PLAN",
        },
      ],
    },
    {
      level: 0,
      label: "Ground · Lobby retail",
      units: [
        {
          id: "u-0a",
          unitLabel: "G1",
          floor: 0,
          title: "Street retail bay",
          sizeM2: 64,
          price: 72000,
          currency: "ETB",
          status: "available",
          listingType: "RENT",
        },
        {
          id: "u-0b",
          unitLabel: "G2",
          floor: 0,
          title: "Corner cafe shell",
          sizeM2: 52,
          price: 64000,
          currency: "ETB",
          status: "sold",
          listingType: "RENT",
        },
      ],
    },
  ],
};
